/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * Amount.
 *
 * <p>Amounts are specified in minor units. For Norwegian kroner (NOK) that means 1 kr &#x3D; 100
 * øre. Example: 499 kr &#x3D; 49900 øre.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class Amount {
  /** Must be in Minor Units. The smallest unit of a currency. Example 100 NOK &#x3D; 10000. */
  private Integer value;
  /** The currency identifier according to ISO 4217. Example: \&quot;NOK\&quot; */
  private String currency;
}
