/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * CheckoutSessionThirdPartyInformationHeaders.
 *
 * <p>Information about the merchant system.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class CheckoutSessionThirdPartyInformationHeaders {
  /**
   * The name of the ecommerce solution. Example: \&quot;Acme Enterprises Ecommerce DeLuxe\&quot;.
   */
  private String vippsSystemName;
  /** The version number of the ecommerce solution. Example: \&quot;3.1.2\&quot;. */
  private String vippsSystemVersion;
  /** The name of the ecommerce plugin. Example: \&quot;acme-webshop\&quot;. */
  private String vippsSystemPluginName;
  /** The version number of the ecommerce plugin. Example: \&quot;4.5.6\&quot;. */
  private String vippsSystemPluginVersion;
}
