/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * CheckoutConfigCustomConsent.
 *
 * <p>If used, displays a checkbox that can be used to ask for extra consent.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class CheckoutConfigCustomConsent {
  /**
   * Text displayed next to the checkbox. This text can contain up to one link in markdown format
   * like this: [linkText](https://example.com)
   */
  private String text;
  /** Whether box has to be checked to complete the checkout. */
  private Boolean required;
}
