/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

/** Elements. */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public enum Elements {

  /** &quot;Full&quot; */
  FULL,

  /** &quot;PaymentAndContactInfo&quot; */
  PAYMENTANDCONTACTINFO,

  /** &quot;PaymentOnly&quot; */
  PAYMENTONLY,
}
