/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** InitiateSessionRequestConfiguration. */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class InitiateSessionRequestConfiguration {
  /**
   * If customer is physically present: \&quot;customer_present\&quot;, otherwise:
   * \&quot;customer_not_present\&quot;.
   */
  private CustomerInteraction customerInteraction;
  /** Adjust the fields and values present in the Checkout. */
  private Elements elements;
  /** */
  private CheckoutConfigCountries countries;
  /**
   * One of the following: \&quot;WEB_REDIRECT\&quot;, \&quot;NATIVE_REDIRECT\&quot;. To ensure
   * having a return URL based on an app URL, use \&quot;NATIVE_REDIRECT\&quot;.
   */
  private UserFlow userFlow;
  /**
   * Requires the customer to consent to share their email and openid sub with the merchant to be
   * able to make a wallet payment (default: false).
   */
  private Boolean requireUserInfo;
  /** */
  private CheckoutConfigCustomConsent customConsent;
  /** Decides whether the order lines are displayed as a shopping cart context in the checkout. */
  private Boolean showOrderSummary;
}
