/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import jakarta.annotation.Nullable;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** InitiateSessionRequestMerchantInfo. */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class InitiateSessionRequestMerchantInfo {
  /**
   * Complete URL for receiving callbacks. Example:
   * \&quot;https://exmaple.com/vipps/payment-callback/
   */
  private String callbackUrl;
  /**
   * Complete URL for redirecting customers to when the checkout is finished. Example:
   * \&quot;https://example.com/vipps\&quot;.
   */
  private String returnUrl;
  /**
   * The token will be supplied by the callback to the merchant as a header. Example:
   * \&quot;iOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJ\&quot;.
   */
  private String callbackAuthorizationToken;
  /**
   * Complete URL to the merchant&#39;s terms and conditions. Example:
   * \&quot;https://example.com/vipps/termsAndConditions\&quot;.
   */
  @Nullable private String termsAndConditionsUrl;
}
