/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * MerchantAuthInfoHeaders.
 *
 * <p>Headers required to retrieve an access token.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class MerchantAuthInfoHeaders {
  /**
   * Client ID for the merchant (the \&quot;username\&quot;). Found in the Vipps portal. Example:
   * \&quot;fb492b5e-7907-4d83-bc20-c7fb60ca35de\&quot;.
   */
  private String clientId;
  /**
   * Client Secret for the merchant (the \&quot;password\&quot;). Found in the Vipps portal.
   * Example: \&quot;Y8Kteew6GE3ZmeycEt6egg&#x3D;&#x3D;\&quot;.
   */
  private String clientSecret;
  /**
   * Vipps Subscription key for the API product. Found in the Vipps portal. Example:
   * \&quot;0f14ebcab0eb4b29ae0cb90d91b4a84a\&quot;.
   */
  private String ocpApimSubscriptionKey;
  /**
   * Vipps assigned unique number for a merchant. Found in the Vipps portal. Example:
   * \&quot;123456\&quot;.
   */
  private String merchantSerialNumber;
}
