/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** PaymentTransaction. */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class PaymentTransaction {
  /** */
  private LogisticsOptionBaseAmount amount;
  /**
   * The merchant&#39;s unique reference for the transaction. Also known as OrderId. Example:
   * \&quot;acme-shop-123-order123abc\&quot;. See
   * https://vippsas.github.io/vipps-developer-docs/docs/vipps-developers/common-topics/orderid
   */
  private String reference;
  /**
   * Description visible to the customer during payment. Example: \&quot;One pair of Vipps
   * socks\&quot;.
   */
  private String paymentDescription;
  /** */
  private PaymentTransactionOrderSummary orderSummary;
}
