/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * PorterbuddyOrigin.
 *
 * <p>Information about the sender
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class PorterbuddyOrigin {
  /** The name of your store */
  private String name;
  /** Your email address where Porterbuddy booking confirmation will be sent */
  private String email;
  /**
   * Your phone number where Porterbuddy may send you important messages. Format must be MSISDN
   * (including country code). Example: \&quot;4791234567\&quot;
   */
  private String phoneNumber;
  /** */
  private PorterbuddyOriginAddress address;
}
