/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

/** QuantityUnit. */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public enum QuantityUnit {

  /** &quot;PCS&quot; */
  PCS,

  /** &quot;KG&quot; */
  KG,

  /** &quot;KM&quot; */
  KM,

  /** &quot;MINUTE&quot; */
  MINUTE,

  /** &quot;LITRE&quot; */
  LITRE,
}
