/*
 * checkout-backend-merchant-v3.API
 * For details, see the [Checkout API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/checkout-api).
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.checkout;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.util.Map;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Singular;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * SessionResponse.
 *
 * <p>Session information
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class SessionResponse {
  /** The Id of the session. Example: \&quot;v52EtjZriRmGiKiAKHByK2\&quot;. */
  private String sessionId;
  /** The merchant&#39;s serial number. Example: \&quot;123456\&quot; */
  private String merchantSerialNumber;
  /**
   * The merchant&#39;s unique reference for the transaction. Also known as OrderId. Example:
   * \&quot;acme-shop-123-order123abc\&quot;. See
   * https://vippsas.github.io/vipps-developer-docs/docs/vipps-developers/common-topics/orderid
   */
  private String reference;
  /**
   * The state of the session. Example: \&quot;SessionStarted\&quot;. The state of the payment is in
   * PaymentDetails.State.
   */
  private ExternalSessionState sessionState;
  /** */
  private PaymentMethod paymentMethod;
  /** */
  private SessionResponsePaymentDetails paymentDetails;
  /** */
  private SessionResponseUserInfo userInfo;
  /** */
  private SessionResponseShippingDetails shippingDetails;
  /** */
  private SessionResponseBillingDetails billingDetails;
  /** */
  private Boolean customConsentProvided;
  @Singular
  @JsonAnySetter
  @JsonAnyGetter
  private Map<String, Object> additionalProperties;
}
