name: Test and publish package
on:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Execute Gradle build
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
          MERCHANT_SERIAL_NUMBER: ${{ secrets.MERCHANT_SERIAL_NUMBER }}
        run: ./gradlew :test --info
      - name: Publish package
        env:
          PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew :publish --info
