/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import java.util.List;
import java.util.UUID;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** Address. */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class Address {
  /** */
  private String city;
  /** Country code according to ISO 3166-2 (two capital letters). */
  private String country;
  /** Unique ID of the address, always provided in response from Vipps. */
  private UUID id;
  /** Array of addressLines, for example street name, number, etc. */
  private List<String> lines;
  /** Postcode of the address in local country format. */
  private String postCode;
}
