/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** Aggregate. */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class Aggregate {
  /** */
  private Amount authorizedAmount;
  /** */
  private Amount cancelledAmount;
  /** */
  private Amount capturedAmount;
  /** */
  private Amount refundedAmount;
}
