/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * Amount.
 *
 * <p>Amount object
 */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class Amount {
  /** */
  private Currency currency;
  /**
   * Integer value of price in the currency&#39;s monetary subunit (e.g., Norwegian øre), or
   * monetary unit where applicable (e.g., Japanese YEN). The type of the monetary unit is defined
   * in ISO 4217.
   */
  private Long value;
}
