/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * CreatePaymentRequestQrFormat.
 *
 * <p>Optional setting that is only applicable when &#x60;userFlow&#x60; is set to &#x60;QR&#x60;.
 * This is used to set the format for the QR code.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class CreatePaymentRequestQrFormat {
  /**
   * If &#x60;userFlow&#x60; is &#x60;QR&#x60; and &#x60;qrFormat&#x60; is not set, the QR code
   * image will be returned as &#x60;SVG+XML&#x60;, by default.
   */
  private Format format;
  /**
   * For example, if the value is 200, then 200x200 px is set as the dimension for the QR code. This
   * is only applicable when the format is set to &#x60;PNG&#x60;. If not set, the default is 1024.
   */
  private Integer size;
}
