/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URI;
import java.util.Map;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Singular;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * CreatePaymentResponse.
 *
 * <p>The &#x60;CreatePaymentResponse&#x60; object.
 */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class CreatePaymentResponse {
  /**
   * The URL to which the user is redirected when continuing the payment for
   * &#x60;NATIVE_REDIRECT&#x60; and &#x60;WEB_REDIRECT&#x60;. When &#x60;userFlow&#x60; is
   * &#x60;QR&#x60;, a link to the QR image (or the target URL) will be returned. Nothing will be
   * returned when &#x60;userFlow&#x60; is &#x60;PUSH_MESSAGE&#x60;.
   */
  private URI redirectUrl;
  /** A reference */
  private String reference;

  @Singular @JsonAnySetter @JsonAnyGetter private Map<String, Object> additionalProperties;
}
