/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/**
 * Customer.
 *
 * <p>Target customer
 */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class Customer {
  /**
   * The phone number of the user paying the transaction with Vipps. Only Norwegian mobile numbers
   * are supported (for now). The format is MSISDN: Digits only: Country code and subscriber number,
   * but no prefix. See: https://en.wikipedia.org/wiki/MSISDN
   */
  private String phoneNumber;
}
