package no.vipps.model.epayment;

/** Generated by NJsonSchema v10.8.0.0 (Newtonsoft.Json v10.0.0.0) */
public enum Format {
  TEXT_TARGETURL("TEXT/TARGETURL"),
  IMAGE_SVG_XML("IMAGE/SVG+XML"),
  IMAGE_PNG("IMAGE/PNG");

  private String value;

  Format(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }
}
