/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

/**
 * PaymentMethodType.
 *
 * <p>The paymentMethod type to be performed. &#x60;CARD&#x60; has to be combined with a
 * &#x60;userFlow&#x60; of &#x60;WEB_REDIRECT&#x60;.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public enum PaymentMethodType {

  /** &quot;WALLET&quot; */
  WALLET,

  /** &quot;CARD&quot; */
  CARD,
}
