/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import java.time.OffsetDateTime;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** PaymentEvent. */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class PaymentEvent {
  /** A reference */
  private String reference;
  /** Reference value for a payment defined by Vipps. */
  private String pspReference;
  /** */
  private PaymentEventName name;
  /** */
  private PaymentAction paymentAction;
  /** */
  private Amount amount;
  /** */
  private OffsetDateTime timestamp;
  /** */
  private OffsetDateTime processedAt;
  /** The Idempotency key of the request. */
  private String idempotencyKey;
  /** The outcome of the event */
  private Boolean success;
}
