/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

import java.net.URI;

/** Problem. */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class Problem {
  /** A URI reference that identifies the problem type. */
  private URI type;
  /**
   * A short, human-readable summary of the problem type. It will not change from occurrence to
   * occurrence of the problem.
   */
  private String title;
  /** A human-readable explanation specific to this occurrence of the problem. */
  private String detail;
  /** An id that can be used to facilitate in tracing the error. */
  private String traceId;
}
