/*
 * Vipps ePayment API
 * The Vipps ePayment API. See the [API Guide](https://vippsas.github.io/vipps-developer-docs/docs/APIs/epayment-api) for more information.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package no.vipps.model.epayment;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.util.Map;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Singular;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;

/** ProfileResponse. */
@Jacksonized
@EqualsAndHashCode
@Getter
@ToString
@Builder
public class ProfileResponse {
  /**
   * If &#x60;profile.scope&#x60; was requested in &#x60;createPayment&#x60; this value will
   * populate once &#x60;state&#x60; is &#x60;AUTHORIZED&#x60;. This can be used towards the Vipps
   * Login Userinfo endpoint to fetch requested user data.
   */
  private String sub;

  @Singular @JsonAnySetter @JsonAnyGetter private Map<String, Object> additionalProperties;
}
